#########################################################################################
## This script calculates the area of all polygons generated by the KDE process and
## outputs CSV files of potential events.
## Bryony Louise Puxley
## Last Edited: Wednesday, August 13th, 2025
## Input: Decadal density files for drought and pluvial events.
## Output: Decadal CSV files (1 for droughts, 1 for pluvials) that have a list of all 
## potential events throughout the time frame, including: Drought Date, Pluvial Date,
## Area (km2), and polygon geometry. 
#########################################################################################
# Import Required Modules
#########################################################################################
import xesmf as xe
import numpy as np
import xarray as xr
import dask
from tqdm import tqdm
import time
from datetime import datetime, timedelta, date
from netCDF4 import Dataset, num2date, MFDataset
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from matplotlib.path import Path
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import spei as si
import pandas as pd
import scipy.stats as scs
import os

#########################################################################################
# Import Functions
#########################################################################################
import functions

